window.PAIA_LIVRE = [
  {id:"preface", vol:1, title:"Préface — Le grand divorce", quote:"L’avenir ne fait pas de prisonniers. Il récompense ceux qui s’adaptent les premiers.", declic:"La question n’est plus si l’IA va transformer votre métier. C’est si vous serez le pilote — ou le remplacé.", arme:"Écrivez : pourquoi j’ai ouvert ce livre ; le changement qui compte ; ma première action.", wb:1, prompts:[1], ch:"Préface"},
  {id:"intro", vol:1, title:"Introduction — Le contrat de lecture", quote:"Ce livre n’est pas un roman. C’est un simulateur.", declic:"Une action de quinze minutes vaut mieux qu’une semaine de théories.", arme:"Signez le contrat : je m’engage à appliquer, pas seulement à lire.", wb:1, prompts:[1], ch:"Introduction"},
  {id:"ch1", vol:1, title:"Ch. 1 — La fin du diplôme-roi", quote:"Les emplois changent. La capacité d’apprendre reste votre avantage.", declic:"La source de votre anxiété n’est pas le changement. C’est l’attente.", arme:"Trois compétences dont vous êtes fier. Une à développer. Une tâche répétitive. Une tâche humaine.", wb:1, prompts:[1,4], ch:"Chapitre 1", cas:"Mariam, Bamako"},
  {id:"ch2", vol:1, title:"Ch. 2 — L’or invisible", quote:"Le défi n’est pas de repartir de zéro. C’est de voir ce que vous savez déjà faire.", declic:"Une compétence n’a pas besoin d’un parchemin pour avoir de la valeur.", arme:"Nuage de valeur : emplois, bénévolat, famille. Reliez chaque activité à une compétence.", wb:2, prompts:[2,6], ch:"Chapitre 2", cas:"Idrissa, Niamey"},
  {id:"ch3", vol:1, title:"Ch. 3 — L’arme secrète", quote:"L’IA ne remplace pas les personnes. Elle transforme la manière dont elles créent de la valeur.", declic:"L’IA n’est pas un oracle. Gardez la main sur le volant.", arme:"Deux colonnes : tâches robots / tâches humaines. Comment nourrir la seconde ?", wb:6, prompts:[3,37], ch:"Chapitre 3", cas:"Awa, Dakar"},
  {id:"ch4", vol:1, title:"Ch. 4 — Le Profil Augmenté", quote:"Votre avenir dépend de votre capacité à évoluer plus vite que les changements.", declic:"À compétences égales, ceux qui dominent collaborent, apprennent vite et parlent juste.", arme:"Une compétence. Une ressource gratuite. Une action minuscule aujourd’hui. Trois créneaux cette semaine.", wb:9, prompts:[10,31], ch:"Chapitre 4", cas:"Jean, Douala"},
  {id:"ch5", vol:2, title:"Ch. 5 — L’eldorado sous nos yeux", quote:"Les plus grandes opportunités naissent là où des problèmes attendent encore des solutions.", declic:"Avant une idée extraordinaire, cherchez un problème ordinaire.", arme:"Nommez votre quartier. Quels services manquent ? Une idée. Une action cette semaine.", wb:11, prompts:[11,91], ch:"Chapitre 5", cas:"Fatou, Abidjan"},
  {id:"ch6", vol:2, title:"Ch. 6 — Le plan de bascule", quote:"Un objectif sans plan reste un souhait. Une action répétée devient une transformation.", declic:"Beaucoup attendent le plan parfait. L’action apporte des informations que la réflexion ne donnera jamais.", arme:"Bloquez trois créneaux de 30 à 45 min pour les 4 prochaines semaines. Une action sous 24 h.", wb:16, prompts:[42,96], ch:"Chapitre 6", cas:"Aminata, Ouagadougou · Serge, Cotonou"},
  {id:"ch7", vol:2, title:"Ch. 7 — Le Manuel du Pilote", quote:"La qualité des réponses dépend de la qualité des questions.", declic:"Traitez chaque prompt comme le brief d’un collaborateur expérimenté. P.R.O.", arme:"Trois briefs testés avec votre situation. Rangez les meilleures réponses.", wb:8, prompts:[16,26,96], ch:"Chapitre 7", cas:"Nadia, Lomé · Moussa, Bamako"},
  {id:"fin", vol:2, title:"Conclusion — Votre avenir commence maintenant", quote:"Le meilleur moment était hier. Le deuxième est aujourd’hui.", declic:"Vous ne prévoirez pas tous les changements. Vous pouvez toujours apprendre, vous adapter, résoudre.", arme:"Trois engagements pour 30 jours. Simples. Réalistes. Mesurables. Signez.", wb:21, prompts:[100], ch:"Conclusion", cas:"Clarisse, Bujumbura"}
];
